@Web_HostAddress = https://localhost:5001

POST {{Web_HostAddress}}/api/Identity/login
Content-Type: application/json

{
  "Email": "administrator@localhost",
  "Password": "Administrator1!"
}

###

POST {{Web_HostAddress}}/api/Identity/register
Content-Type: application/json

{
  "Email":"jeff@test.com",
  "Password":"Secret1234#"
}

###

POST {{Web_HostAddress}}/api/Identity/login
Content-Type: application/json

{
  "Email": "jeff@test.com",
  "Password": "Secret1234#"
}
