name: CICD

on: 
  push:
    branches: 
      - dev
      - main
    paths-ignore:
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md

permissions:
  id-token: write
  contents: read

jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true

  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    needs: [ build ]
    with:
      environmentName:  
        ${{(github.ref == 'refs/heads/main' && 'production') ||
          (github.ref == 'refs/heads/staging' && 'staging') ||
          (startsWith(github.ref, 'refs/heads/feature/') && 'development') ||
          'development'}}

 # deploy-staging:
 #   uses: ./.github/workflows/deploy.yml
 #   secrets: inherit
 #   needs: [ deploy-development ]
 #   with:
 #     environmentName: Staging

 # deploy-production:
 #   uses: ./.github/workflows/deploy.yml
 #   secrets: inherit
 #   needs: [ deploy-staging ]
 #   with:
 #    environmentName: Production
